### PR TITLE
Select games and users

### PR DESCRIPTION
**Pull request by lovellk**
When creating a game and creating a copy, drop down fields allow you to select games and users by name. @ChrstphrHll @adam-kosinski

### CODE REVIEW

**Comment by adam-kosinski** [comment]
Breaks with a SQL error if you have a typo in your game name

**Comment by adam-kosinski** [comment]
Otherwise good

**Comment by adam-kosinski** [comment]
Oh also creating a copy seems to fail if you don't specify a borrower name

**Comment by lovellk** [comment]
All fixed. Merging.

**Pull request merged**
