### PR TITLE
Navbar styling

### PR DESCRIPTION
**Pull request by lovellk**
Navbar touchups. It was so hideous I actually did it in my free time.

1. Navbar now looks pretty. Verify it looks pretty.
2. Navbar is now responsive, if you zoom in or preview on mobile, it will turn into a dropdown.
3. Navbar buttons should route properly.
4. User button appears only if a user is signed in.
- You need to be signed into a user which has data in the database since we don't support inserting stuff yet. TLDR: test on an existing user. Example: email: squirrel@tree.net, Password: qwerty. Other users are in the users.csv file we load.
- Make sure the "Your Games", "Your Collections", and "Your Recommended" redirect you to the corresponding page for your uid.

### CODE REVIEW

**Comment by adam-kosinski** [comment]
Looks good. I kinda want to have the user's profile pic and username on the navbar as well to more clearly let the user know they are logged in (somewhat similar to in the page mockups), but this is less important. You can merge.

**Comment by ChrstphrHll** [comment]
👍

**Comment by lovellk** [comment]
> Looks good. I kinda want to have the user's profile pic and username on the navbar as well to more clearly let the user know they are logged in (somewhat similar to in the page mockups), but this is less important. You can merge.

I agree. When we have that type of info in the database I will replace the logout button with the user dropdown and see how that breaks things later.

**Comment by lovellk** [comment]
Navbar styling.

**Pull request merged**
