### PR TITLE
Game grid looks awesome

### PR DESCRIPTION
**Pull request by adam-kosinski**
Take a look at liked games, it looks so good. And that page is now literally one line of code.

It's also compatible with pagination etc, just replace the table with the macro.

@ChrstphrHll I can replace the recommended games and main game search with this macro very easily if you would like, it shouldn't break anything.

### CODE REVIEW

**Comment by lovellk** [comment]
I kind of wish it took up more of the page. It seems weird that its only like maybe 1/2 of it. Where did the descriptions go? Also, is it possible to maybe make these arrows look a bit less weird?
image
image

**Comment by adam-kosinski** [comment]
Descriptions were never there to begin with, those are only for the individual game page. The arrows were from before, I'm feeling a bit too lazy to change those, @ChrstphrHll can if he wants. For me it seems to be taking up most of the page

**Comment by lovellk** [comment]
image

**Comment by lovellk** [comment]
I think Christopher can change it, don't worry. I'll just merge.

**Pull request merged**
